name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and test with Maven
        run: mvn --batch-mode clean verify

      # - name: Archive artifacts (optional)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifact
      #     path: target/*.jar
